config/routes.rb
Rails.application.routes.draw do
  resources :cities do
    member do
      post :update_temp
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = City.all
  end

  def update_temp
    city = City.find(params[:id])
    response = RestClient.get "http://v.juhe.cn/weather/index",
                              :params => { :cityname => city.juhe_id, :key => JUHE_CONFIG["api_key"] }
    data = JSON.parse(response.body)
    city.update( :current_temp => data["result"]["sk"]["temp"] )

    redirect_to cities_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/index.html.erb
<table class="table">
  <tr>
    <th>Juhe ID</th>
    <th>Province</th>
    <th>City</th>
    <th>District</th>
    <th>Temp</th>
  </tr>
  <% @cities.each do |city| %>
    <tr>
      <td><%= city.juhe_id %></td>
      <td><%= city.province %></td>
      <td><%= city.city %></td>
      <td><%= city.district %></td>
      <td>
        <%= city.current_temp %>
        <%= link_to "更新温度", update_temp_city_path(city), :method => :post %>
      </td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiExercise</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>